# Generated by Django 3.2.6 on 2021-09-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
