# Generated by Django 3.2.6 on 2021-09-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='publisher',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
