# Generated by Django 3.2.6 on 2021-10-07 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField()),
                ('description', models.TextField(default='')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='shows_app.networks')),
            ],
        ),
    ]
